In [6]:
import numpy as np
import pandas as pd
filename = "datasets/diamonds.csv"
df = pd.read_csv(filename)

df.head(107)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
5,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
6,7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47
7,8,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
9,10,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39
10,11,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73
11,12,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46
12,13,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33
13,14,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71
14,15,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27
15,16,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68
16,17,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68
17,18,0.30,Good,J,SI1,63.4,54.0,351,4.23,4.29,2.70
18,19,0.30,Good,J,SI1,63.8,56.0,351,4.23,4.26,2.71
19,20,0.30,Very Good,J,SI1,62.7,59.0,351,4.21,4.27,2.66
20,21,0.30,Good,I,SI2,63.3,56.0,351,4.26,4.30,2.71
21,22,0.23,Very Good,E,VS2,63.8,55.0,352,3.85,3.92,2.48
22,23,0.23,Very Good,H,VS1,61.0,57.0,353,3.94,3.96,2.41
23,24,0.31,Very Good,J,SI1,59.4,62.0,353,4.39,4.43,2.62
24,25,0.31,Very Good,J,SI1,58.1,62.0,353,4.44,4.47,2.59
25,26,0.23,Very Good,G,VVS2,60.4,58.0,354,3.97,4.01,2.41
26,27,0.24,Premium,I,VS1,62.5,57.0,355,3.97,3.94,2.47
27,28,0.30,Very Good,J,VS2,62.2,57.0,357,4.28,4.30,2.67
28,29,0.23,Very Good,D,VS2,60.5,61.0,357,3.96,3.97,2.40
29,30,0.23,Very Good,F,VS1,60.9,57.0,357,3.96,3.99,2.42
...,...,...,...,...,...,...,...,...,...,...,...
77,78,0.26,Very Good,D,VVS2,62.4,54.0,554,4.08,4.13,2.56
78,79,0.26,Very Good,D,VVS2,62.8,60.0,554,4.01,4.05,2.53
79,80,0.26,Very Good,E,VVS1,62.6,59.0,554,4.06,4.09,2.55
80,81,0.26,Very Good,E,VVS1,63.4,59.0,554,4.00,4.04,2.55
81,82,0.26,Very Good,D,VVS1,62.1,60.0,554,4.03,4.12,2.53
82,83,0.26,Ideal,E,VVS2,62.9,58.0,554,4.02,4.06,2.54
83,84,0.38,Ideal,I,SI2,61.6,56.0,554,4.65,4.67,2.87
84,85,0.26,Good,E,VVS1,57.9,60.0,554,4.22,4.25,2.45
85,86,0.24,Premium,G,VVS1,62.3,59.0,554,3.95,3.92,2.45
86,87,0.24,Premium,H,VVS1,61.2,58.0,554,4.01,3.96,2.44
87,88,0.24,Premium,H,VVS1,60.8,59.0,554,4.02,4.00,2.44
88,89,0.24,Premium,H,VVS2,60.7,58.0,554,4.07,4.04,2.46
89,90,0.32,Premium,I,SI1,62.9,58.0,554,4.35,4.33,2.73
90,91,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57
91,92,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52
92,93,0.70,Ideal,G,VS2,61.6,56.0,2757,5.70,5.67,3.50
93,94,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56
94,95,0.78,Very Good,G,SI2,63.8,56.0,2759,5.81,5.85,3.72
95,96,0.70,Good,E,VS2,57.5,58.0,2759,5.85,5.90,3.38
96,97,0.70,Good,F,VS1,59.4,62.0,2759,5.71,5.76,3.40
97,98,0.96,Fair,F,SI2,66.3,62.0,2759,6.27,5.95,4.07
98,99,0.73,Very Good,E,SI1,61.6,59.0,2760,5.77,5.78,3.56
99,100,0.80,Premium,H,SI1,61.5,58.0,2760,5.97,5.93,3.66
100,101,0.75,Very Good,D,SI1,63.2,56.0,2760,5.80,5.75,3.65
101,102,0.75,Premium,E,SI1,59.9,54.0,2760,6.00,5.96,3.58
102,103,0.74,Ideal,G,SI1,61.6,55.0,2760,5.80,5.85,3.59
103,104,0.75,Premium,G,VS2,61.7,58.0,2760,5.85,5.79,3.59
104,105,0.80,Ideal,I,VS1,62.9,56.0,2760,5.94,5.87,3.72
105,106,0.75,Ideal,G,SI1,62.2,55.0,2760,5.87,5.80,3.63
106,107,0.80,Premium,G,SI1,63.0,59.0,2760,5.90,5.81,3.69

In [7]:
df.describe()

,Unnamed: 0,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [9]:
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [10]:
df.tail()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [12]:
df.dtypes

Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [13]:
df.count()

Unnamed: 0    53940
carat         53940
cut           53940
color         53940
clarity       53940
depth         53940
table         53940
price         53940
x             53940
y             53940
z             53940
dtype: int64

In [14]:
df['price'].sum()

212135217

In [15]:
df['price'].mean()

3932.799721913237

In [16]:
df['price'].mode()

0    605
dtype: int64

In [17]:
df['carat'].mean()

0.7979397478679852

In [19]:
df['price'].std()

3989.4397381463023

In [20]:
df.count()

Unnamed: 0    53940
carat         53940
cut           53940
color         53940
clarity       53940
depth         53940
table         53940
price         53940
x             53940
y             53940
z             53940
dtype: int64

In [21]:
df.groupby('price')

In [22]:
df['carat'].groupby(df['price']).mean()

price
326      0.220000
327      0.230000
334      0.290000
335      0.310000
336      0.240000
337      0.240000
338      0.230000
339      0.300000
340      0.230000
342      0.220000
344      0.310000
345      0.260000
348      0.300000
351      0.300000
352      0.230000
353      0.283333
354      0.230000
355      0.240000
357      0.242500
358      0.260000
360      0.290000
361      0.272500
362      0.242500
363      0.298000
364      0.233333
365      0.320000
366      0.330000
367      0.225294
368      0.300000
369      0.230000
           ...
18717    2.180000
18718    1.700000
18729    1.510000
18730    1.720000
18731    2.020000
18735    1.940000
18736    2.010000
18741    2.010000
18745    2.360000
18756    2.610000
18757    2.030000
18759    2.000000
18760    2.080000
18766    2.550000
18768    1.710000
18777    1.510000
18779    2.060000
18780    1.600000
18781    2.030000
18784    2.050000
18787    2.050000
18788    2.800000
18791    1.930000
18795    2.020000
18797    2.290000
18803    2.000000
18804    2.070000
18806    1.510000
18818    2.000000
18823    2.290000
Name: carat, Length: 11602, dtype: float64

In [23]:
pd.pivot_table(df, index=['cut'])

,Unnamed: 0,carat,depth,price,table,x,y,z
cut,,,,,,,,
Fair,24147.357764,1.046137,64.041677,4358.757764,59.053789,6.246894,6.182652,3.982770
Good,24774.931309,0.849185,62.365879,3928.864452,58.694639,5.838785,5.850744,3.639507
Ideal,29047.630736,0.702837,61.709401,3457.541970,55.951668,5.507451,5.520080,3.401448
Premium,25600.209049,0.891955,61.264673,4584.257704,58.746095,5.973887,5.944879,3.647124
Very Good,26097.313193,0.806381,61.818275,3981.759891,57.956150,5.740696,5.770026,3.559801

In [24]:
pd.pivot_table(df, values=['price'], index=['cut'])

                 price
cut
Fair       4358.757764
Good       3928.864452
Ideal      3457.541970
Premium    4584.257704
Very Good  3981.759891

In [25]:
pd.pivot_table(df, values=['price', 'clarity'], index=['cut'])

                 price
cut
Fair       4358.757764
Good       3928.864452
Ideal      3457.541970
Premium    4584.257704
Very Good  3981.759891

In [26]:
pd.pivot_table(df, values=['cut', 'clarity', 'table'], index=['price'])

           table
price
326    58.000000
327    65.000000
334    58.000000
335    58.000000
336    57.000000
337    58.000000
338    61.000000
339    55.000000
340    56.000000
342    61.000000
344    54.000000
345    60.000000
348    54.000000
351    56.250000
352    55.000000
353    60.333333
354    58.000000
355    57.000000
357    57.875000
358    56.000000
360    55.500000
361    58.250000
362    56.500000
363    57.200000
364    53.666667
365    59.000000
366    54.000000
367    58.176471
368    58.333333
369    58.000000
...          ...
18717  60.000000
18718  59.000000
18729  57.000000
18730  60.000000
18731  59.000000
18735  58.000000
18736  57.000000
18741  58.000000
18745  58.000000
18756  56.000000
18757  55.800000
18759  60.000000
18760  60.000000
18766  62.000000
18768  55.000000
18777  59.000000
18779  55.000000
18780  56.000000
18781  60.000000
18784  59.000000
18787  57.000000
18788  58.000000
18791  56.500000
18795  59.500000
18797  59.000000
18803  57.000000
18804  55.000000
18806  55.000000
18818  56.000000
18823  60.000000

[11602 rows x 1 columns]

In [30]:
df['carat'].count

<bound method Series.count of 0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
5        0.24
6        0.24
7        0.26
8        0.22
9        0.23
10       0.30
11       0.23
12       0.22
13       0.31
14       0.20
15       0.32
16       0.30
17       0.30
18       0.30
19       0.30
20       0.30
21       0.23
22       0.23
23       0.31
24       0.31
25       0.23
26       0.24
27       0.30
28       0.23
29       0.23
         ...
53910    0.70
53911    0.57
53912    0.61
53913    0.80
53914    0.84
53915    0.77
53916    0.74
53917    0.90
53918    0.76
53919    0.76
53920    0.70
53921    0.70
53922    0.70
53923    0.73
53924    0.73
53925    0.79
53926    0.71
53927    0.79
53928    0.79
53929    0.71
53930    0.71
53931    0.71
53932    0.70
53933    0.70
53934    0.72
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64>

In [31]:
df['clarity'].count()

53940

In [35]:
df['x'].std()

1.1217607467924422

In [36]:
pd.pivot_table(df, values=['x', 'y', 'z'], index=df['price'])

              x         y         z
price
326    3.920000  3.910000  2.370000
327    4.050000  4.070000  2.310000
334    4.200000  4.230000  2.630000
335    4.340000  4.350000  2.750000
336    3.945000  3.970000  2.475000
337    3.970000  3.945000  2.510000
338    4.000000  4.050000  2.390000
339    4.250000  4.280000  2.730000
340    3.930000  3.900000  2.460000
342    3.880000  3.840000  2.330000
344    4.350000  4.370000  2.710000
345    4.085000  4.085000  2.475000
348    4.310000  4.340000  2.680000
351    4.232500  4.280000  2.695000
352    3.850000  3.920000  2.480000
353    4.256667  4.286667  2.540000
354    3.970000  4.010000  2.410000
355    3.970000  3.940000  2.470000
357    3.993750  4.007500  2.477500
358    4.080000  4.160000  2.550000
360    4.265000  4.285000  2.640000
361    4.167500  4.202500  2.560000
362    3.962500  3.995000  2.487500
363    4.258000  4.288000  2.660000
364    3.950000  3.983333  2.463333
365    4.370000  4.410000  2.730000
366    4.430000  4.450000  2.770000
367    3.910000  3.898824  2.403529
368    4.280000  4.315000  2.668333
369    3.890000  3.913333  2.446667
...         ...       ...       ...
18717  8.380000  8.300000  5.100000
18718  7.700000  7.750000  4.620000
18729  7.340000  7.400000  4.530000
18730  7.650000  7.680000  4.740000
18731  8.110000  8.200000  4.880000
18735  7.910000  7.870000  4.940000
18736  8.070000  8.090000  5.020000
18741  8.093333  8.033333  4.986667
18745  8.690000  8.750000  5.180000
18756  8.850000  8.730000  5.460000
18757  8.170000  8.300000  4.950000
18759  8.280000  8.340000  4.810000
18760  8.360000  8.400000  4.920000
18766  8.700000  8.650000  5.360000
18768  7.660000  7.630000  4.750000
18777  7.330000  7.240000  4.560000
18779  8.150000  8.190000  5.080000
18780  7.470000  7.520000  4.650000
18781  8.000000  7.930000  5.020000
18784  8.280000  8.330000  5.000000
18787  8.100000  8.160000  5.030000
18788  8.900000  8.850000  0.000000
18791  7.930000  7.940000  4.955000
18795  8.250000  8.150000  4.875000
18797  8.520000  8.450000  5.240000
18803  7.950000  8.000000  5.010000
18804  8.200000  8.130000  5.110000
18806  7.370000  7.410000  4.560000
18818  7.900000  7.970000  5.040000
18823  8.500000  8.470000  5.160000

[11602 rows x 3 columns]

In [37]:
df.groupby(['carat']).mean()

,Unnamed: 0,depth,table,price,x,y,z
carat,,,,,,,
0.20,28965.166667,61.100000,59.333333,365.166667,3.786667,3.753333,2.303333
0.21,34659.000000,60.511111,58.444444,380.222222,3.874444,3.837778,2.332222
0.22,6948.600000,61.620000,60.400000,391.400000,3.898000,3.848000,2.386000
0.23,35756.993174,61.426621,58.034130,486.143345,3.946382,3.973379,2.431468
0.24,31885.330709,61.599213,57.488189,505.185039,3.990157,4.019331,2.465591
0.25,27251.905660,61.565566,57.363208,550.924528,4.062500,4.086934,2.506934
0.26,25794.683794,61.677470,56.911858,550.897233,4.102688,4.124704,2.536364
0.27,26385.497854,61.599142,56.778970,574.759657,4.159142,4.181588,2.567897
0.28,29973.500000,61.526263,56.863636,580.121212,4.207172,4.233687,2.595707
0.29,29105.807692,61.393077,56.846154,601.192308,4.262846,4.290538,2.624000
0.30,31137.293779,61.914631,57.134217,680.301843,4.299443,4.308061,2.664351
0.31,30463.686972,61.758382,56.700845,708.235660,4.353219,4.360912,2.690422
0.32,29539.675000,61.726685,56.592337,720.144022,4.399821,4.406995,2.717755
0.33,30529.696384,61.573003,56.777544,765.731707,4.449521,4.456569,2.741447
0.34,30100.005495,61.588132,56.798681,756.380220,4.495363,4.499560,2.768714
0.35,32537.433283,61.600150,56.776162,800.676162,4.544693,4.550825,2.801049
0.36,31562.347902,61.505944,56.877797,781.381119,4.580927,4.590105,2.819266
0.37,32771.431472,61.363706,57.169289,816.071066,4.625228,4.632944,2.839949
0.38,34228.929851,61.428209,56.833284,904.441791,4.662403,4.677313,2.866955
0.39,34733.424623,61.546985,57.090955,922.331658,4.696156,4.713593,2.898116
0.40,34850.511162,61.891686,57.200000,932.784450,4.727991,4.738199,2.928922
0.41,36100.290159,61.820188,56.972214,973.627352,4.769247,4.775427,2.949906
0.42,36662.317280,61.656516,56.865297,994.444759,4.814717,4.821303,2.970354
0.43,36677.522541,61.610246,57.013934,995.192623,4.851844,4.859816,2.991168
0.44,37873.066038,61.526415,57.277358,1056.622642,4.892594,4.900189,3.012123
0.45,38519.072727,61.880000,57.703636,1093.318182,4.920545,4.908273,3.040545
0.46,40582.292135,61.821910,57.025843,1237.533708,4.952135,4.965281,3.064775
0.47,40689.626263,61.464646,57.426263,1272.313131,5.001212,5.010101,3.076869
0.48,41522.793651,61.188889,57.588889,1322.047619,5.045714,5.061429,3.090794
0.49,41760.866667,60.660000,58.595556,1306.333333,5.108444,5.097556,3.094444
...,...,...,...,...,...,...,...
2.64,27164.000000,62.300000,55.000000,17407.000000,8.880000,8.830000,5.520000
2.65,26593.000000,62.000000,61.000000,16314.000000,8.820000,8.750000,5.450000
2.66,26908.666667,63.966667,58.000000,16991.000000,8.710000,8.650000,5.553333
2.67,27673.000000,63.800000,58.000000,18686.000000,8.690000,8.640000,5.540000
2.68,20717.000000,61.050000,58.000000,9042.000000,8.960000,8.920000,5.455000
2.70,25526.000000,63.100000,56.000000,14341.000000,8.840000,8.780000,5.560000
2.71,27017.000000,60.400000,59.000000,17146.000000,9.130000,9.030000,5.480000
2.72,22693.666667,63.300000,55.666667,12088.333333,8.866667,8.830000,5.590000
2.74,24851.333333,63.233333,60.333333,14385.000000,8.836667,8.800000,5.573333
2.75,25457.500000,60.700000,59.000000,14285.500000,9.015000,8.975000,5.485000
2.77,22400.000000,62.600000,62.000000,10424.000000,8.930000,8.830000,5.560000
2.80,26820.500000,62.450000,58.500000,16909.000000,8.965000,8.915000,2.750000
3.00,23317.250000,61.987500,60.375000,12378.500000,9.198750,9.066250,5.657500
3.01,25944.642857,61.821429,58.857143,15910.285714,9.230000,9.150714,5.677857
3.02,22541.000000,65.200000,56.000000,10577.000000,9.110000,9.020000,5.910000
3.04,26870.000000,61.250000,59.500000,16956.500000,9.325000,9.265000,5.685000
3.05,22429.000000,60.900000,58.000000,10453.000000,9.260000,9.250000,5.660000
3.11,21759.000000,65.900000,57.000000,9823.000000,9.150000,9.020000,5.980000
3.22,24298.000000,62.600000,55.000000,12545.000000,9.490000,9.420000,5.920000
3.24,24132.000000,62.100000,58.000000,12300.000000,9.440000,9.400000,5.850000
3.40,26432.000000,66.800000,52.000000,15964.000000,9.420000,9.340000,6.270000
3.50,24329.000000,62.800000,57.000000,12587.000000,9.650000,9.590000,6.030000
3.51,27680.000000,62.500000,59.000000,18701.000000,9.660000,9.630000,6.030000
3.65,23645.000000,67.100000,53.000000,11668.000000,9.530000,9.480000,6.380000
3.67,26535.000000,62.400000,56.000000,16193.000000,9.860000,9.810000,6.130000
4.00,26445.000000,63.300000,58.000000,15984.000000,10.010000,9.940000,6.310000
4.01,25999.500000,61.750000,61.500000,15223.000000,10.080000,10.020000,6.205000
4.13,27131.000000,64.800000,61.000000,17329.000000,10.000000,9.850000,6.430000
4.50,27631.000000,65.800000,58.000000,18531.000000,10.230000,10.160000,6.720000
5.01,27416.000000,65.500000,59.000000,18018.000000,10.740000,10.540000,6.980000

In [40]:
df.groupby(['depth','carat', 'table','price']).mean()

                         Unnamed: 0     x     y     z
depth carat table price
43.0  1.00  59.0  3634       4519.0  6.32  6.27  3.97
      1.09  54.0  4778      10378.0  6.53  6.55  4.12
44.0  1.00  53.0  4032       6342.0  6.31  6.24  4.12
50.8  1.43  60.0  6727      16858.0  7.73  7.25  3.93
51.0  0.30  67.0  945       36504.0  4.67  4.62  2.37
52.2  0.70  65.0  1895      47776.0  6.04  5.99  3.14
52.3  0.37  61.0  1166      40767.0  4.96  4.91  2.58
52.7  0.56  70.0  1293      42257.0  5.71  5.57  2.97
53.0  1.02  63.0  2856        714.0  6.84  6.77  3.66
53.1  0.96  63.0  2815        444.0  6.73  6.65  3.55
53.2  0.35  62.0  1011      38042.0  4.87  4.80  2.57
      1.26  61.0  4966      11242.0  7.44  7.36  3.94
53.3  0.98  67.0  2855        713.0  6.82  6.74  3.61
53.4  0.73  65.0  2164      49806.0  6.19  6.15  3.30
53.8  1.08  63.0  4790      10465.0  6.99  6.81  3.71
54.0  0.34  56.0  1012      38054.0  4.80  4.76  2.58
54.2  0.31  63.0  814       33017.0  4.61  4.51  2.47
            65.0  997       37746.0  4.61  4.58  2.49
54.3  0.53  65.0  1352      42805.0  5.46  5.51  2.98
54.4  0.25  64.0  1013      38154.0  4.30  4.23  2.32
54.6  0.35  59.0  1011      38041.0  4.85  4.79  2.63
54.7  0.78  67.0  2691      53543.0  6.25  6.15  3.40
55.0  0.75  66.0  1827      47110.0  6.20  6.04  3.37
      0.99  61.0  2812        424.0  6.72  6.67  3.68
55.1  0.62  66.0  1641      45058.0  5.85  5.70  3.18
      0.84  67.0  2782        228.0  6.39  6.20  3.47
      0.86  69.0  2757         92.0  6.45  6.33  3.52
55.2  0.25  64.0  361       28271.0  4.21  4.23  2.33
      0.34  59.0  1040      38642.0  4.72  4.77  2.62
      0.48  60.0  907       35663.0  5.29  5.25  2.91
...                             ...   ...   ...   ...
69.7  0.98  58.0  1712      45829.0  6.08  5.98  4.21
      1.50  56.0  4704       9983.0  6.94  6.90  4.82
      1.52  55.0  4648       9677.0  6.92  6.89  4.81
69.8  0.50  55.0  584        8393.0  4.89  4.80  3.38
      1.00  54.0  4435       8576.0  6.03  5.94  4.18
      2.00  54.0  5914      14646.0  7.60  7.56  5.29
69.9  1.00  61.0  2117      49496.0  6.13  5.86  4.23
70.0  1.83  58.0  5083      11779.0  7.34  7.28  5.12
70.1  1.50  58.0  4328       8015.0  6.96  6.85  4.84
      2.22  55.0  6564      16440.0  7.77  7.74  5.44
70.2  1.00  58.0  2326      51008.0  6.00  5.73  4.13
      2.00  57.0  15351     26100.0  7.63  7.59  5.34
      2.01  57.0  6315      15782.0  7.53  7.50  5.27
70.5  2.32  55.0  6860      17182.0  7.93  7.90  5.58
70.6  0.70  56.0  1828      47126.0  5.45  5.35  3.81
      1.02  57.0  4398       8357.0  6.08  6.01  4.27
      2.01  64.0  18574     27647.0  7.43  6.64  4.69
70.8  0.70  56.0  992       37677.0  5.38  5.33  3.79
      0.73  55.0  1049      38841.0  5.51  5.34  3.84
71.0  0.50  57.0  613       17718.0  4.87  4.79  3.43
71.2  0.85  54.0  1274      42105.0  5.77  5.65  4.07
71.3  1.50  58.0  4368       8187.0  6.85  6.81  4.87
71.6  0.70  55.0  1696      45689.0  5.47  5.28  3.85
      0.99  57.0  3593       4308.0  5.94  5.80  4.20
71.8  1.02  56.0  4455       8673.0  6.04  5.97  4.31
72.2  0.96  56.0  2438      51929.0  6.01  5.81  4.28
72.9  0.90  54.0  2691      53541.0  5.74  5.67  4.16
73.6  0.99  60.0  1789      46680.0  6.01  5.80  4.35
78.2  1.03  54.0  1262      41919.0  5.72  5.59  4.42
79.0  0.50  73.0  2579      52861.5  5.21  5.18  4.09

[52488 rows x 4 columns]

In [42]:
df.groupby(['depth','carat', 'table','price']).std()

                         Unnamed: 0    x    y    z
depth carat table price
43.0  1.00  59.0  3634          NaN  NaN  NaN  NaN
      1.09  54.0  4778          NaN  NaN  NaN  NaN
44.0  1.00  53.0  4032          NaN  NaN  NaN  NaN
50.8  1.43  60.0  6727          NaN  NaN  NaN  NaN
51.0  0.30  67.0  945           NaN  NaN  NaN  NaN
52.2  0.70  65.0  1895          NaN  NaN  NaN  NaN
52.3  0.37  61.0  1166          NaN  NaN  NaN  NaN
52.7  0.56  70.0  1293          NaN  NaN  NaN  NaN
53.0  1.02  63.0  2856          NaN  NaN  NaN  NaN
53.1  0.96  63.0  2815          NaN  NaN  NaN  NaN
53.2  0.35  62.0  1011          NaN  NaN  NaN  NaN
      1.26  61.0  4966          NaN  NaN  NaN  NaN
53.3  0.98  67.0  2855          NaN  NaN  NaN  NaN
53.4  0.73  65.0  2164          NaN  NaN  NaN  NaN
53.8  1.08  63.0  4790          NaN  NaN  NaN  NaN
54.0  0.34  56.0  1012          NaN  NaN  NaN  NaN
54.2  0.31  63.0  814           NaN  NaN  NaN  NaN
            65.0  997           NaN  NaN  NaN  NaN
54.3  0.53  65.0  1352          NaN  NaN  NaN  NaN
54.4  0.25  64.0  1013          NaN  NaN  NaN  NaN
54.6  0.35  59.0  1011          NaN  NaN  NaN  NaN
54.7  0.78  67.0  2691          NaN  NaN  NaN  NaN
55.0  0.75  66.0  1827          NaN  NaN  NaN  NaN
      0.99  61.0  2812          NaN  NaN  NaN  NaN
55.1  0.62  66.0  1641          NaN  NaN  NaN  NaN
      0.84  67.0  2782          NaN  NaN  NaN  NaN
      0.86  69.0  2757          NaN  NaN  NaN  NaN
55.2  0.25  64.0  361           NaN  NaN  NaN  NaN
      0.34  59.0  1040          NaN  NaN  NaN  NaN
      0.48  60.0  907           NaN  NaN  NaN  NaN
...                             ...  ...  ...  ...
69.7  0.98  58.0  1712          NaN  NaN  NaN  NaN
      1.50  56.0  4704          NaN  NaN  NaN  NaN
      1.52  55.0  4648          NaN  NaN  NaN  NaN
69.8  0.50  55.0  584           NaN  NaN  NaN  NaN
      1.00  54.0  4435          NaN  NaN  NaN  NaN
      2.00  54.0  5914          NaN  NaN  NaN  NaN
69.9  1.00  61.0  2117          NaN  NaN  NaN  NaN
70.0  1.83  58.0  5083          NaN  NaN  NaN  NaN
70.1  1.50  58.0  4328          NaN  NaN  NaN  NaN
      2.22  55.0  6564          NaN  NaN  NaN  NaN
70.2  1.00  58.0  2326          NaN  NaN  NaN  NaN
      2.00  57.0  15351         NaN  NaN  NaN  NaN
      2.01  57.0  6315          NaN  NaN  NaN  NaN
70.5  2.32  55.0  6860          NaN  NaN  NaN  NaN
70.6  0.70  56.0  1828          NaN  NaN  NaN  NaN
      1.02  57.0  4398          NaN  NaN  NaN  NaN
      2.01  64.0  18574         NaN  NaN  NaN  NaN
70.8  0.70  56.0  992           NaN  NaN  NaN  NaN
      0.73  55.0  1049          NaN  NaN  NaN  NaN
71.0  0.50  57.0  613           NaN  NaN  NaN  NaN
71.2  0.85  54.0  1274          NaN  NaN  NaN  NaN
71.3  1.50  58.0  4368          NaN  NaN  NaN  NaN
71.6  0.70  55.0  1696          NaN  NaN  NaN  NaN
      0.99  57.0  3593          NaN  NaN  NaN  NaN
71.8  1.02  56.0  4455          NaN  NaN  NaN  NaN
72.2  0.96  56.0  2438          NaN  NaN  NaN  NaN
72.9  0.90  54.0  2691          NaN  NaN  NaN  NaN
73.6  0.99  60.0  1789          NaN  NaN  NaN  NaN
78.2  1.03  54.0  1262          NaN  NaN  NaN  NaN
79.0  0.50  73.0  2579     0.707107  0.0  0.0  0.0

[52488 rows x 4 columns]

In [43]:
pd.pivot_table(df, values=['depth', 'table'], index=['price'])

           depth      table
price
326    60.650000  58.000000
327    56.900000  65.000000
334    62.400000  58.000000
335    63.300000  58.000000
336    62.550000  57.000000
337    63.500000  58.000000
338    59.400000  61.000000
339    64.000000  55.000000
340    62.800000  56.000000
342    60.400000  61.000000
344    62.200000  54.000000
345    60.550000  60.000000
348    62.000000  54.000000
351    63.300000  56.250000
352    63.800000  55.000000
353    59.500000  60.333333
354    60.400000  58.000000
355    62.500000  57.000000
357    61.912500  57.875000
358    61.900000  56.000000
360    61.750000  55.500000
361    61.200000  58.250000
362    62.525000  56.500000
363    62.260000  57.200000
364    62.100000  53.666667
365    62.200000  59.000000
366    62.400000  54.000000
367    61.541176  58.176471
368    62.100000  58.333333
369    62.700000  58.000000
...          ...        ...
18717  61.200000  60.000000
18718  59.800000  59.000000
18729  61.500000  57.000000
18730  61.800000  60.000000
18731  59.800000  59.000000
18735  62.600000  58.000000
18736  62.100000  57.000000
18741  61.866667  58.000000
18745  59.400000  58.000000
18756  62.100000  56.000000
18757  60.000000  55.800000
18759  57.900000  60.000000
18760  58.700000  60.000000
18766  61.800000  62.000000
18768  62.100000  55.000000
18777  62.600000  59.000000
18779  62.200000  55.000000
18780  62.000000  56.000000
18781  63.000000  60.000000
18784  60.200000  59.000000
18787  61.900000  57.000000
18788  63.800000  58.000000
18791  62.450000  56.500000
18795  59.450000  59.500000
18797  61.800000  59.000000
18803  62.800000  57.000000
18804  62.500000  55.000000
18806  61.700000  55.000000
18818  63.500000  56.000000
18823  60.800000  60.000000

[11602 rows x 2 columns]

In [44]:
pd.pivot_table(df, values=['depth', 'table'], index=['price']).mean()

depth    61.707768
table    57.662686
dtype: float64

In [45]:
pd.pivot_table(df, values=['depth', 'table'], index=['price']).mode()

   depth  table
0   62.0   58.0

In [46]:
pd.pivot_table(df, values=['depth', 'table'], index=['price']).std()

depth    1.073050
table    1.624959
dtype: float64

In [47]:
pd.pivot_table(df, values=['depth', 'table'], index=['price']).median()

depth    61.754196
table    57.571429
dtype: float64

In [48]:
pd.pivot_table(df, values=['depth', 'table'], index=['price']).describe()

              depth         table
count  11602.000000  11602.000000
mean      61.707768     57.662686
std        1.073050      1.624959
min       53.200000     52.000000
25%       61.200000     56.666667
50%       61.754196     57.571429
75%       62.300000     58.556746
max       70.600000     70.000000